### ISSUE TITLE
Interface enhance Quest log

### ISSUE THREAD

**Issue by neverke1** [leatrix/leatrix-plus-bcc#31] opened 2021-06-15 17:13 UTC
Makes the questlog wide, but it doesn't want to show quest levels for me. I have to use another addon for that.
Those addons might be conflicting, but i'm pretty sure it's a leatrix bug. Since it briefly shows quest level then it doesn't. 
If it works fine for you guys, then it might be just a me issue, if that's the case i would appreciate some insight on what could be the cause for it. 

Another question.. could we enhance the quest log in another way? make the window longer? to show us more quests.

Thank you for this addon btw. It's awesome, keep it up :D

**Comment by leatrix** [comment] 2021-06-15 17:18
Disable all other addons.  Does it work?  Not possible to provide insight without knowing more information.

**Comment by leatrix** [comment] 2021-07-05 10:36
Closing as no updates in 20 days.  Issue likely caused by another addon.

**Closed by leatrix** 2021-07-05 10:36 UTC
Labels: help
