### ISSUE TITLE
Auto invite not working.

### ISSUE THREAD

**Issue by SneakyCowz** [leatrix/leatrix-plus-bcc#24] opened 2021-06-11 15:47 UTC
For some reason auto invite is not working. Anyone else getting this issue?

![image](https://user-images.githubusercontent.com/47327222/121713324-04ad9500-cadd-11eb-9218-15d4ca5092cc.png)

**Comment by leatrix** [comment] 2021-06-11 16:01
Click the configuration button next to the 'Invite from whispers' option and ensure the checkbox is set correctly.

**Comment by SneakyCowz** [comment] 2021-06-11 16:40
Pretty sure it is. I've tried typing "inv" into it many times now. Copying a text, placing it in the Keyword and then pasting it into whisper
![image](https://user-images.githubusercontent.com/47327222/121721335-71785d80-cae4-11eb-9b4e-cc7daf0a6f9b.png)

**Comment by leatrix** [comment] 2021-06-11 16:46
Disable other addons and test again.  It's working fine for me.

**Comment by SneakyCowz** [comment] 2021-06-11 16:57
I've tried with everything except Leatrix Plus disabled now. 1 by 1 and also with LTP as the only addon active.
No luck yet :(

**Comment by leatrix** [comment] 2021-06-11 17:07
It's working fine for me and there have been no other reports.  If you type /invite <char name> does the invite work?

**Comment by leatrix** [comment] 2021-06-11 17:14
The invite isn't sent if the recipient is queued for a battleground.  Is that the case?

**Comment by SneakyCowz** [comment] 2021-06-11 17:17
Ah. And thus the troubleshooting is complete! Thank you very very much!
Is there any way I can manually turn that setting off and on?

**Comment by leatrix** [comment] 2021-06-11 17:43
No because if someone whispers you with the keyword while you are queued for a battleground and there is no queue check in place, it can reset your battleground queue timer.  In the latest alpha, the option tooltip now states that it doesn't send the invite if you are queued for a battleground.

**Comment by SneakyCowz** [comment] 2021-06-11 18:05
Fair if it's the norm.
From my perspective it would be very helpful though :)
I have had no problems with inviting or being invited by people during my BG queues. Yet! ^^
In any case, thanks for helping me out.

**Comment by spidor** [comment] 2021-06-21 17:28
I can confirm that there is something going on with the auto invite. I'm not in BG queue, and it invite some people, but some it doesn't. They are all in my guild and the setting is set to invite guild members and friends only.

**Comment by leatrix** [comment] 2021-06-21 19:28
How many people in your guild and how many are online when you use invite from whispers?  Is there anything in common with the people who don't get invited (i.e. perhaps the people who get invited are same realm and people who don't are different realm)?  Are the people that don't get invited new to the guild?  Do you get the same result with all other addons disabled?  Finally, do a test with the 'guild members and friends only' checkbox unchecked.  Does that fix it?

**Comment by spidor** [comment] 2021-06-22 08:42
> How many people in your guild and how many are online when you use invite from whispers? Is there anything in common with the people who don't get invited (i.e. perhaps the people who get invited are same realm and people who don't are different realm)? Are the people that don't get invited new to the guild? Do you get the same result with all other addons disabled? Finally, do a test with the 'guild members and friends only' checkbox unchecked. Does that fix it?

Didn't notice anything that is common atm. All people are on the same realm, and with the same guild role, all of them are online. The online thing I could think of, is that people who are not online on Bnet, may not be invited, but can't confirm it yet. I'll try to find something that makes it easier the replicate the issue.

**Comment by leatrix** [comment] 2021-06-22 12:54
The Invite from whispers option doesn't send invites to people who are showing offline because they are appearing offline to the game so LTP sees them as offline too.  I'll update the tooltip with this information.

**Comment by spidor** [comment] 2021-06-23 07:41
> The Invite from whispers option doesn't send invites to people who are showing offline because they are appearing offline to the game so LTP sees them as offline too. I'll update the tooltip with this information.

It seems that even if they offline on Bnet, they still get the invite if they whisper me ingame (not on Bnet). Could there be a cooldown on the invites? So it won't invite the second person if they whisper me the same time?

**Comment by leatrix** [comment] 2021-06-23 12:52
For character whispers, characters cannot appear offline so if the character is in your friends list or guild (or if you don't have the friend and guild restriction box checked), the invite will be sent because LTP will see the character as online.  You can see this for yourself - if a character is in your friends list but they have their battle.net status set to appear offline, you will still see their character online in your friends list (or guild).  So a message from a character is received, LTP sees the character name and sends the invite.

For Battle.net messages, it's different.  LTP receives the Battle.net message but then needs to query the BattleTag for the character name (because invites are sent to the character, not the BattleTag, so LTP needs to know the character name).  But the query only works if the Battle.net friend is online.  If they are appearing offline, the query won't return a character name so an invite won't be sent.

**Comment by spidor** [comment] 2021-06-23 12:59
> For character whispers, characters cannot appear offline so if the character is in your friends list or guild (or if you don't have the friend and guild restriction box checked), the invite will be sent because LTP will see the character as online. You can see this for yourself - if a character is in your friends list but they have their battle.net status set to appear offline, you will still see their character online in your friends list (or guild). So a message from a character is received, LTP sees the character name and sends the invite.
> 
> For Battle.net messages, it's different. LTP receives the Battle.net message but then needs to query the BattleTag for the character name (because invites are sent to the character, not the BattleTag, so LTP needs to know the character name). But the query only works if the Battle.net friend is online. If they are appearing offline, the query won't return a character name so an invite won't be sent.

Sounds reasonable. Today I'll have a raid, so I'll test the invite again. I'll get back to you if I figure out, why it is not inviting some people.

**Comment by leatrix** [comment] 2021-07-05 10:37
Closing as no updates in 12 days.

**Closed by leatrix** 2021-07-05 10:37 UTC
Labels: help
