### ISSUE TITLE
Flight Path Progress Timer Not Showing After Update

### ISSUE THREAD

**Issue by ltpgithub007** [leatrix/leatrix-plus-bcc#88] opened 2022-01-11 00:34 UTC
After I updated today, the flight progress timer no longer shows. I tried disabling it and reenabling it and reloading the UI to no avail. Is there a bug in the newest update causing the flight timer to not work? Please help, this was one of my favorite features of LTP.

**Comment by leatrix** [comment] 2022-01-11 01:14
It's working absolutely fine for me.  I downloaded it from CurseForge and installed it.  Tested it with English and German locales on BCC.  All fine.

Are you sure that the flight you are taking has a flight time saved for it?  To find out, just open up the flight map and hover the pointer over a destination flight point.  If the flight time appears in the flight point tooltip, LTP has a flight time for that flight and the bar should appear.  If the flight time doesn't appear in the tooltip, LTP doesn't have a flight time for that flight so the bar won't appear but you will see the report window when you land from that flight.

Failing that, try disabling all other addons to see if the bar appears then (for a flight that has a flight time showing in the flight map tooltip).  Something else to try is restart the game client completely (not just reload but a full client restart).

**Comment by ltpgithub007** [comment] 2022-01-12 20:05
Yeah so it's really strange, it works on and off for flight paths that 100% have flight time saved for them. Also I noticed the durability inside the character items hasn't been showing. I had to download an entirely separate addon to get that going again. But even with that addon, the durability is showing on and off, and with that addon it has other features that deal with showing other items in the character panel that aren't showing up on and off. Not sure what's happening but it must be something on Blizzard's end with them modifying game files and it affecting addons like this. I've restarted the client, reloaded, etc. but it still is an on and off issue.

**Comment by leatrix** [comment] 2022-01-12 20:12
It works fine and it's not Blizzard's fault.  Did you try disabling ALL other addons (double-check to make sure all other addons are disabled as people often miss one or two)?  If there was a problem with multiple settings such as durability and the flight progress bar, there would be more than one ticket for it.

**Comment by ltpgithub007** [comment] 2022-01-12 20:39
Yeah I have I don't know what's going on

**Comment by leatrix** [comment] 2022-01-12 20:50
You've already said it's not caused by Leatrix Plus because you have problems with other addons too when Leatrix Plus isn't installed.

So if you're sure you have disabled all other addons, you can test it with other characters if you wish (same result or different?) and you can show me screenshots if you wish (or perhaps a video).  You might want to try a scan and repair for your Wow installation (click the cogwheel next to the Play button in the Battle.net launcher).

**Comment by leatrix** [comment] 2022-01-16 17:15
Closing this as from your information, it's not an issue caused by Leatrix Plus.

**Closed by leatrix** 2022-01-16 17:15 UTC
Labels: help
