### ISSUE TITLE
leatrix-plus-wotlk?

### ISSUE THREAD

**Issue by jazminite** [leatrix/leatrix-plus-bcc#111] opened 2022-07-21 21:49 UTC
Is there a repo for Wrath yet to post issues? Here's what happens when I try to load the TBC version of the addons on Beta:
![image](https://user-images.githubusercontent.com/65823478/180321084-383da45c-1192-4952-abac-e3d9994f38c4.png)

**Comment by leatrix** [comment] 2022-07-21 22:14
Blizzard, in their infinite wisdom, enabled addons in Wrath Beta so players can use addons like Leatrix Plus in Wrath Classic.  Except they didn't give Leatrix access to Wrath Beta so Leatrix cannot code Leatrix Plus for Wrath Classic.

What can I say?  When Blizzard give me access to their game, I will code the addons for their game.

**Comment by jazminite** [comment] 2022-07-21 23:00
Ok. If you want any help, I have access.

**Comment by leatrix** [comment] 2022-07-24 15:54
In the latest alpha releases of all Leatrix addons for BCC, you will no longer see the wrong version installed messages and the addons will **attempt** to run in Wrath Beta.  I have no idea if you will see error messages or what works and what doesn't.

Leatrix Plus is fully modular so you may see error messages after enabling particular settings and if you do, just disable those settings.  Leatrix Maps is partially modular.

In CurseForge App, you can easily switch to alpha releases.  Just right-click the addon in your addon listing and choose release type > alpha.  You can change it back to release type > release anytime you like.

**Comment by jazminite** [comment] 2022-07-24 16:34
Thanks. I tested version [2.5.116.alpha.6-bcc](https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/3896531). Auto repair and sell junk working properly. Not sure why I bought an Elemental Flux but that's probably a different addon.
![image](https://user-images.githubusercontent.com/65823478/180656991-c086e2a1-69cd-4157-a0e7-507c7a40fa21.png)

**Comment by leatrix** [comment] 2022-07-26 11:51
Yes that will be a different addon.  There is nothing in LTP which automatically buys items from vendors.  Test as much as you want in the addons.

**Comment by leatrix** [comment] 2022-07-27 10:17
Blizzard are being real dicks about Wrath beta access.  Still no access to Wrath beta.  I'm adding this here because I'm linking this to everyone that emails me or sends me CurseForge messages about Wrath Beta (and there are many of you so thank you for your support).

If Blizzard give me access to Wrath Beta, all addons will be updated within a day of me getting that access.
If not, I will update everything when the pre-patch is made public.

If you want to complain to Blizzard that they are being dicks for depriving players from using popular addons in Wrath Beta by denying access to the author of said addons, be my guest and link to this page.

**Comment by kriminy** [comment] 2022-07-28 18:07
Do you want us to report Lua errors and bugs we come across? I understand you're not able to test the add-on yourself, but I'm willing to help if possible. I just enabled it, and I noticed due to the Wrath changes, the "Enhance Quest Log" feature is no longer working.

**Comment by leatrix** [comment] 2022-07-28 18:16
You can by all means report issues.  The problem is that I'm not going to be able to fix them until I can login to the beta and when I can do that, I will see the issues anyway (the issues that I see will be fixed quickly when I can login).

LTP is modular so if any settings cause issues, you only need to disable those particular settings.  Disabled settings don't do anything.

If you wish to contact Blizzard to complain about their decision to deny me beta access and it's effect on players who are forced to use out-of-date addons as a result of their decision, you can email CommunityEMEA@blizzard.com.

**Comment by leatrix** [comment] 2022-08-04 15:29
The latest BCC alpha releases of Leatrix Plus and Leatrix Maps are compatible with Wrath Classic.

If you use CurseForge App, right-click the addon in your addon listing and set the release type to alpha.  Keep it as alpha until Wrath Classic launches for everyone.

If you use the CurseForge website instead of the app, you can download alpha releases from [here](https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all) for Leatrix Plus or [here](https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all) for Leatrix Maps but that's going to be more tedious than using the app.

These are only the first alpha releases for Wrath Classic.  More will follow and your bug reports will be very useful.

**Closed** 2022-08-17 06:58 UTC
Labels: help
