### ISSUE TITLE
Latest release causes Windows Defender to detect update of LTP and LTM as virus

### ISSUE THREAD

**Issue by Trust-WoW** [leatrix/leatrix-plus-bcc#55] opened 2021-08-18 19:07 UTC
Latest release causes Windows Defender to detect update of LTP and LTM as virus

**Comment by leatrix** [comment] 2021-08-18 19:19
Do you have a screenshot?  Obviously, it's a false positive.
VirusTotal links for [LTP](https://www.virustotal.com/gui/file-analysis/YmJjYTAyYmIzMTliNzQxYTAzZWNjZjcyYzc2ZjIyMjc6MTYyOTMxMzk4OA==/detection) and [LTM](https://www.virustotal.com/gui/file/27b3034cf333d8dcea5a7b21afe0bdd031a5611ae5b6f67244a5a53bd343ef6b/detection).

**Comment by Kolmarwow** [comment] 2021-08-18 21:13
This seems to be an issue with the very latest update of Windows Defender. I heard of another person having this issue and I tried updating Leatrix Plus through various means (manual / Curseforge addon manager / Ajour addon manager) and it all worked fine, then I refreshed Windows Update and it installed a new Defender patch and now it flags LTP as a trojan no matter if i download it manually or through an addon manager. 

![leatrixscreenshot](https://user-images.githubusercontent.com/28187000/129972998-393a07d1-4870-4bdf-9928-a6fb3cc46f42.png)

**Comment by leatrix** [comment] 2021-08-18 22:33
Thanks for the additional information, it's very helpful.  It does seem to be an issue with Windows Defender.  Microsoft's cloud scan reports false positives in the zip files but not in any of the files contained within the zip files.  I have submitted the false positives to Microsoft so that they can update Windows Defender definitions.

Just for the record for future readers, addons for Wow don't contain viruses.  Addons are compiled by the game and run in a restricted environment so they can only do what Blizzard has expressly permitted them to do.

**Comment by leatrix** [comment] 2021-08-19 06:36
Microsoft have informed me that they have removed the false positives for LTM-BCC and LTP-BCC in the latest definitions.

Quote from Microsoft (same for both LTM and LTP):

> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Plus-SL and Maps-Classic false positives should be cleared soon.  No other Leatrix addons are affected.

**Comment by leatrix** [comment] 2021-08-19 07:39
After further investigation, it seems that the false positives were caused by incorrectly formatted translations.  In many cases, a translation that simply had additional spaces at the end caused CurseForge to compile the translations incorrectly.  Windows Defender interpreted the malformed translations as code infected with malware (how it came to that conclusion is a mystery).

The malformed translations will be fixed in updates for each affected addon.

**Comment by leatrix** [comment] 2021-08-19 12:05
Addons have now been updated (where needed).  The latest updates should no longer show false positives in Windows Defender.

**Closed** 2021-08-25 10:21 UTC
Labels: help
